name: Build CLI

permissions:
    contents: read

on:
    pull_request:
        branches:
            - 'main'
    push:
        branches:
            - 'main'

jobs:
    cli:
        name: Build, Test, and Lint CLI Module
        runs-on: ubuntu-latest

        steps:
            - name: Checkout PR Branch
              uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

            - name: Setup Node.js
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                  node-version: v22

            - name: Install workspace
              run: npm ci

            - name: Lint CLI Module
              run: npm run lint --workspace=cli

            - name: Build workspace
              run: npm run build:cli

            - name: Run tests with coverage for CLI
              run: npm run test --workspace=cli
