name: Build Docs

permissions:
    contents: read

on:
    pull_request:
        branches:
            - 'main'
    push:
        branches:
            - 'main'

jobs:
    docs:
        name: Build Docs Module
        runs-on: ubuntu-latest

        steps:
            - name: Checkout PR Branch
              uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

            - name: Setup Node.js
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                  node-version: v22
                  cache: npm
                  cache-dependency-path: package-lock.json

            - name: Install workspace
              run: npm ci

            - name: Build Docs
              run: npm run build:docs
