name: PR Labeler

permissions:
    contents: read
    pull-requests: write

on:
    pull_request_target:
        types: [opened, synchronize]

jobs:
    label:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

            - name: Label PR based on changes
              uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # v4
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
