name: Publish CLI to NPM

permissions:
    contents: write # needed for semantic-release to create releases and update files
    issues: write # needed for semantic-release to comment on issues
    pull-requests: write # needed for semantic-release to comment on PRs

on:
    release:
        types: [published]

jobs:
    publish-cli:
        runs-on: ubuntu-latest
        steps:
            # Checkout the code
            - name: Checkout code
              uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
              with:
                  fetch-depth: 0 # semantic-release needs full git history

            # Set up Node.js
            - name: Setup Node.js
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                  node-version: v22
                  registry-url: 'https://registry.npmjs.org'

            # Install the workspace
            - name: Install workspace
              run: npm ci

            # Build the entire workspace
            - name: Build workspace
              run: npm run build

            # Update CLI version using semantic-release
            - name: Update CLI version with semantic-release
              run: npm run semantic-release --workspace cli
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            # Publish the CLI module (semantic-release will handle this, but keeping as fallback)
            - name: Publish CLI module
              run: npm publish --workspace cli
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
