name: Sync Videos to S3

permissions:
    contents: read

on:
    workflow_dispatch: {}
    push:
        branches:
            - main
        paths:
            - 'video'

jobs:
    sync-to-s3:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
            - name: Sync video folder to S3
              run: |
                  aws s3 sync video s3://${{ vars.AWS_S3_BUCKET }}/video
