name: Semgrep

permissions:
    contents: read

on:
    workflow_dispatch: {}
    pull_request: {}
    push:
        branches:
            - main
        paths:
            - .github/workflows/semgrep-ci.yml
    schedule:
        # random HH:MM to avoid a load spike on GitHub Actions at 00:00
        - cron: '09 15 * * *'
jobs:
    semgrep:
        name: semgrep/ci
        runs-on: ubuntu-24.04
        env:
            SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        container:
            image: semgrep/semgrep@sha256:62aaded52737fc401299d994f29fcd3d4049bd90bbb77407eca2e29e51ab0d98
        if: (github.actor != 'dependabot[bot]')
        steps:
            - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
            - run: semgrep ci
