name: Semgrep

permissions:
    contents: read

on:
    workflow_dispatch: {}
    pull_request: {}
    push:
        branches:
            - main
        paths:
            - .github/workflows/semgrep-ci.yml
    schedule:
        # random HH:MM to avoid a load spike on GitHub Actions at 00:00
        - cron: '09 15 * * *'
jobs:
    semgrep:
        name: semgrep/ci
        runs-on: ubuntu-24.04
        env:
            SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        container:
            image: semgrep/semgrep@sha256:4eb1dee397683d976f525d689d42d9023617c1c886abae9e4a4590aa96e05028
        if: (github.actor != 'dependabot[bot]')
        steps:
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
            - run: semgrep ci
